name: Basic-Claims
author: SpeedyG(YSO)
version: 1.0
main: com.speedyg.obclaim.Claim
depend: [Vault]
commands:
  kirala:
    description: Eklentinin genel komutudur.
    aliases: [kirayer,kiralayer, yerkirala, yer, yeral, claim, claimal]
  kiralaadmin:
    description: Eklentinin admin komutudur.
    aliases: [kiralaa, cadmin, cadmin]
  silinenler:
    description: Eklentinin admin komutudur.
    aliases: [silinen, sarsa, sarsalar, silinena]